#!/usr/bin/env bash
set -euo pipefail

mkdir -p /run/sshd
ssh-keygen -A

exec /usr/sbin/sshd -D -e \
  -o AllowUsers=zed \
  -o AuthorizedKeysFile=.ssh/authorized_keys \
  -o KbdInteractiveAuthentication=no \
  -o PasswordAuthentication=no \
  -o PermitRootLogin=no \
  -o UsePAM=no
